package EtherHack.Ether;

public class EtherConfig
{

    public Color mainUIAccentColor;
    public Color vehicleUIColor;
    public Color zombieUIColor;
    public Color playerUIColor;
    public Color survivorUIColor;
    public Color remoteSurvivorUIColor;
    public Color itemUIColor;
    public Color worldItemUIColor;
    public Color pushableUIColor;
    public Color buildingUIColor;
    public Color roomUIColor;
    public boolean isAlwaysRack;
    public boolean isAlwaysRoundChamber;
    public boolean isAlwaysRepaired;
    public boolean isAlwaysKnockdown;
    public boolean isAlwaysCritical;
    public boolean isAlwaysAiming;
    public boolean isPlayerInSafeTeleported;
    public boolean isMultiHitZombies;
    public boolean isTimedActionCheat;
    public boolean isEnableGodMode;
    public boolean isEnableNoclip;
    public boolean isEnableInvisible;
    public boolean isEnableNightVision;
    public boolean isZombieDontAttack;
    public boolean isNoRecoil;
    public boolean isNoReload;
    public boolean isNoJam;
    public boolean isNoSpentRoundChamber;
    public boolean isNoBroken;
    public boolean isNoInfected;
    public boolean isNoWet;
    public boolean isNoHoled;
    public boolean isNoDirted;
    public boolean isNoBlooded;
    public boolean isBypassDebugMode;
    public boolean isUnlimitedCarry;
    public boolean isUnlimitedCondition;
    public boolean isUnlimitedEndurance;
    public boolean isUnlimitedAmmo;
    public boolean isDisableFatigue;
    public boolean isDisableHunger;
    public boolean isDisableThirst;
    public boolean isDisableDrunkenness;
    public boolean isDisableAnger;
    public boolean isDisableFear;
    public boolean isDisablePain;
    public boolean isDisablePanic;
    public boolean isDisableMorale;
    public boolean isDisableStress;
    public boolean isDisableSickness;
    public boolean isDisableStressFromCigarettes;
    public boolean isDisableSanity;
    public boolean isDisableBoredomLevel;
    public boolean isDisableUnhappynessLevel;
    public boolean isDisableWetness;
    public boolean isDisableInfectionLevel;
    public boolean isDisableFakeInfectionLevel;
    public boolean isDisableFire;
    public boolean isOptimalCalories;
    public boolean isOptimalWeight;
    public boolean isVisualsEnable;
    public boolean isVisualsPlayersEnable;
    public boolean isVisualsVehiclesEnable;
    public boolean isVisualsZombiesEnable;
    public boolean isVisualDrawToLocalPlayer;
    public boolean isVisualDrawPlayerNickname;
    public boolean isVisualDrawPlayerInfo;
    public boolean isVisualDrawLineToVehicle;
    public boolean isVisualDrawLineToPlayers;
    public boolean isVisualEnable360Vision;
    public boolean isMapDrawLocalPlayer;
    public boolean isMapDrawAllPlayers;
    public boolean isMapDrawVehicles;
    public boolean isMapDrawZombies;
    public boolean isMapDrawBuildings;
    public boolean isMapDrawSurvivors;
    public boolean isMapDrawRemoteSurvivors;
    public boolean isMapDrawPushables;
    public boolean isMapDrawItems;
    public boolean isMapDrawWorldItems;
    public boolean isMapDrawRooms;

    public void saveConfig(String configFileName) {
        Properties config = new Properties();
        //config.setProperty("", Boolean.toString(this.));
        config.setProperty("mainUIAccentColor", ColorUtils.colorToString(this.mainUIAccentColor));
        config.setProperty("vehicleUIColor", ColorUtils.colorToString(this.vehicleUIColor));
        config.setProperty("zombieUIColor", ColorUtils.colorToString(this.zombieUIColor));
        config.setProperty("playerUIColor", ColorUtils.colorToString(this.playerUIColor));
        config.setProperty("survivorUIColor", ColorUtils.colorToString(this.survivorUIColor));
        config.setProperty("remoteSurvivorUIColor", ColorUtils.colorToString(this.remoteSurvivorUIColor));
        config.setProperty("itemUIColor", ColorUtils.colorToString(this.itemUIColor));
        config.setProperty("worldItemUIColor", ColorUtils.colorToString(this.worldItemUIColor));
        config.setProperty("pushableUIColor", ColorUtils.colorToString(this.pushableUIColor));
        config.setProperty("roomUIColor", ColorUtils.colorToString(this.roomUIColor));
        config.setProperty("buildingsUIColor", ColorUtils.colorToString(this.buildingUIColor));
        config.setProperty("isAlwaysRack", Boolean.toString(this.isAlwaysRack));
        config.setProperty("isAlwaysRoundChamber", Boolean.toString(this.isAlwaysRoundChamber));
        config.setProperty("isAlwaysRepaired", Boolean.toString(this.isAlwaysRepaired));
        config.setProperty("isAlwaysKnockdown", Boolean.toString(this.isAlwaysKnockdown));
        config.setProperty("isAlwaysAiming", Boolean.toString(this.isAlwaysAiming));
        config.setProperty("isAlwaysCritical", Boolean.toString(this.isAlwaysCritical));
        config.setProperty("isPlayerInSafeTeleported", Boolean.toString(this.isPlayerInSafeTeleported));
        config.setProperty("isMultiHitZombies", Boolean.toString(this.isMultiHitZombies));
        config.setProperty("isPlayerInSafeTeleported", Boolean.toString(this.isPlayerInSafeTeleported));
        config.setProperty("isMultiHitZombies", Boolean.toString(this.isMultiHitZombies));
        config.setProperty("isTimedActionCheat", Boolean.toString(this.isTimedActionCheat));
        config.setProperty("isEnableGodMode", Boolean.toString(this.isEnableGodMode));
        config.setProperty("isEnableNoclip", Boolean.toString(this.isEnableNoclip));
        config.setProperty("isEnableInvisible", Boolean.toString(this.isEnableInvisible));
        config.setProperty("isEnableNightVision", Boolean.toString(this.isEnableNightVision));
        config.setProperty("isZombieDontAttack", Boolean.toString(this.isZombieDontAttack));
        config.setProperty("isAlwaysRack", Boolean.toString(this.isNoJam));
        config.setProperty("isNoRecoil", Boolean.toString(this.isNoRecoil));
        config.setProperty("isNoReload", Boolean.toString(this.isNoReload));
        config.setProperty("isNoJam", Boolean.toString(this.isNoJam));
        config.setProperty("isNoSpentRoundChamber", Boolean.toString(this.isNoSpentRoundChamber));
        config.setProperty("isNoBroken", Boolean.toString(this.isNoBroken));
        config.setProperty("isNoInfected", Boolean.toString(this.isNoInfected));
        config.setProperty("isNoWet", Boolean.toString(this.isNoWet)); 
        config.setProperty("isNoHoled", Boolean.toString(this.isNoHoled));
        config.setProperty("isNoDirted", Boolean.toString(this.isNoDirted));
        config.setProperty("isNoBlooded", Boolean.toString(this.isNoBlooded));
        config.setProperty("isBypassDebugMode", Boolean.toString(this.isBypassDebugMode));
        config.setProperty("isUnlimitedCarry", Boolean.toString(this.isUnlimitedCarry));
        config.setProperty("isUnlimitedCondition", Boolean.toString(this.isUnlimitedCondition));
        config.setProperty("isUnlimitedEndurance", Boolean.toString(this.isUnlimitedEndurance));
        config.setProperty("isUnlimitedAmmo", Boolean.toString(this.isUnlimitedAmmo));
        config.setProperty("isDisableFatigue", Boolean.toString(this.isDisableFatigue));
        config.setProperty("isDisableHunger", Boolean.toString(this.isDisableHunger));
        config.setProperty("isDisableThirst", Boolean.toString(this.isDisableThirst));
        config.setProperty("isDisableDrunkenness", Boolean.toString(this.isDisableDrunkenness));
        config.setProperty("isDisableAnger", Boolean.toString(this.isDisableAnger));
        config.setProperty("isDisableFear", Boolean.toString(this.isDisableFear));
        config.setProperty("isDisablePain", Boolean.toString(this.isDisablePain));
        config.setProperty("isDisablePanic", Boolean.toString(this.isDisablePanic));
        config.setProperty("isDisableMorale", Boolean.toString(this.isDisableMorale));
        config.setProperty("isDisableStress", Boolean.toString(this.isDisableStress));
        config.setProperty("isDisableSickness", Boolean.toString(this.isDisableSickness));
        config.setProperty("isDisableStressFromCigarettes", Boolean.toString(this.isDisableStressFromCigarettes));
        config.setProperty("isDisableSanity", Boolean.toString(this.isDisableSanity));
        config.setProperty("isDisableBoredomLevel", Boolean.toString(this.isDisableBoredomLevel));
        config.setProperty("isDisableUnhappynessLevel", Boolean.toString(this.isDisableUnhappynessLevel));
        config.setProperty("isDisableWetness", Boolean.toString(this.isDisableWetness));
        config.setProperty("isDisableInfectionLevel", Boolean.toString(this.isDisableInfectionLevel));
        config.setProperty("isDisableFire", Boolean.toString(this.isDisableFire));
        config.setProperty("isDisableFakeInfectionLevel", Boolean.toString(this.isDisableFakeInfectionLevel));
        config.setProperty("isOptimalCalories", Boolean.toString(this.isOptimalCalories));
        config.setProperty("isOptimalWeight", Boolean.toString(this.isOptimalWeight));
        config.setProperty("isVisualsEnable", Boolean.toString(this.isVisualsEnable));
        config.setProperty("isVisualsPlayersEnable", Boolean.toString(this.isVisualsPlayersEnable));
        config.setProperty("isVisualsVehiclesEnable", Boolean.toString(this.isVisualsVehiclesEnable));
        config.setProperty("isVisualsZombiesEnable", Boolean.toString(this.isVisualsZombiesEnable));
        config.setProperty("isVisualDrawToLocalPlayer", Boolean.toString(this.isVisualDrawToLocalPlayer));
        config.setProperty("isVisualDrawPlayerNickname", Boolean.toString(this.isVisualDrawPlayerNickname));
        config.setProperty("isVisualDrawPlayerInfo", Boolean.toString(this.isVisualDrawPlayerInfo));
        config.setProperty("isVisualDrawLineToVehicle", Boolean.toString(this.isVisualDrawLineToVehicle));
        config.setProperty("isVisualDrawLineToPlayers", Boolean.toString(this.isVisualDrawLineToPlayers));
        config.setProperty("isVisualEnable360Vision", Boolean.toString(this.isVisualEnable360Vision));
        config.setProperty("isMapDrawLocalPlayer", Boolean.toString(this.isMapDrawLocalPlayer));
        config.setProperty("isMapDrawAllPlayers", Boolean.toString(this.isMapDrawAllPlayers));
        config.setProperty("isMapDrawVehicles", Boolean.toString(this.isMapDrawVehicles));
        config.setProperty("isMapDrawZombies", Boolean.toString(this.isMapDrawZombies));
        config.setProperty("isMapDrawBuildings", Boolean.toString(this.isMapDrawBuildings));
        config.setProperty("isMapDrawPushables", Boolean.toString(this.isMapDrawPushables));
        config.setProperty("isMapDrawRooms", Boolean.toString(this.isMapDrawRooms));
        config.setProperty("isMapDrawSurvivors", Boolean.toString(this.isMapDrawSurvivors));
        config.setProperty("isMapDrawRemoteSurvivors", Boolean.toString(this.isMapDrawRemoteSurvivors));
        try (FileOutputStream out = new FileOutputStream("EtherHack/config/" + configFileName + ".properties");){
            config.store(out, null);
        }
        catch (IOException e) {
            Logger.printLog((String)("Error while saving config: " + e));
            return;
        }
    }

    public void loadConfig(String configFileName) {
        Properties config = new Properties();
        try (FileInputStream fis = new FileInputStream("EtherHack/config/" + configFileName + ".properties");){
            config.load(fis);
        }
        catch (IOException e) {
            Logger.printLog((String)"The config file was not found. Loading canceled.");
            return;
        }
        //this. = ConfigUtils.getBooleanFromConfig(config, "", false);
        //this. = ConfigUtils.getColorFromConfig(config, "", new Color(0, 0, 0));
        this.mainUIAccentColor = ConfigUtils.getColorFromConfig(config, "mainUIAccentColor", new Color(56, 239, 125));
        this.vehicleUIColor = ConfigUtils.getColorFromConfig(config, "vehicleUIColor", new Color(150, 150, 200));
        this.zombieUIColor = ConfigUtils.getColorFromConfig(config, "zombieUIColor", new Color(255, 150, 100));
        this.playerUIColor = ConfigUtils.getColorFromConfig(config, "playerUIColor", new Color(255, 50, 100));
        this.survivorUIColor = ConfigUtils.getColorFromConfig(config, "survivorUIColor", new Color(0, 0, 0));
        this.remoteSurvivorUIColor = ConfigUtils.getColorFromConfig(config, "remoteSurvivorUIColor", new Color(0, 0, 0));
        this.itemUIColor = ConfigUtils.getColorFromConfig(config, "itemUIColor", new Color(0, 0, 0));
        this.worldItemUIColor = ConfigUtils.getColorFromConfig(config, "worldItemUIColor", new Color(0, 0, 0));
        this.roomUIColor = ConfigUtils.getColorFromConfig(config, "roomUIColor", new Color(0, 0, 0));
        this.buildingUIColor = ConfigUtils.getColorFromConfig(config, "buildingUIColor", new Color(0, 0, 0));
        this.pushableUIColor = ConfigUtils.getColorFromConfig(config, "pushableUIColor", new Color(0, 0, 0));
        this.isAlwaysRack = ConfigUtils.getBooleanFromConfig(config, "isAlwaysRack", false);
        this.isAlwaysRoundChamber = ConfigUtils.getBooleanFromConfig(config, "isAlwaysRoundChamber", false);
        this.isAlwaysRepaired = ConfigUtils.getBooleanFromConfig(config, "isAlwaysRepaired", false);
        this.isAlwaysKnockdown = ConfigUtils.getBooleanFromConfig(config, "isAlwaysKnockdown", false);
        this.isAlwaysAiming = ConfigUtils.getBooleanFromConfig(config, "isAlwaysAiming", false);
        this.isAlwaysCritical = ConfigUtils.getBooleanFromConfig(config, "isAlwaysCritical", false);
        this.isPlayerInSafeTeleported = ConfigUtils.getBooleanFromConfig(config, "isPlayerInSafeTeleported", false);
        this.isMultiHitZombies = ConfigUtils.getBooleanFromConfig(config, "isMultiHitZombies", false);
        this.isTimedActionCheat = ConfigUtils.getBooleanFromConfig(config, "isTimedActionCheat", false);
        this.isEnableGodMode = ConfigUtils.getBooleanFromConfig(config, "isEnableGodMode", false);
        this.isEnableNoclip = ConfigUtils.getBooleanFromConfig(config, "isEnableNoclip", false);
        this.isEnableInvisible = ConfigUtils.getBooleanFromConfig(config, "isEnableInvisible", false);
        this.isEnableNightVision = ConfigUtils.getBooleanFromConfig(config, "isEnableNightVision", false);
        this.isZombieDontAttack = ConfigUtils.getBooleanFromConfig(config, "isZombieDontAttack", false);
        this.isNoRecoil = ConfigUtils.getBooleanFromConfig(config, "isNoRecoil", false);
        this.isNoReload = ConfigUtils.getBooleanFromConfig(config, "isNoReload", false);
        this.isNoJam = ConfigUtils.getBooleanFromConfig(config, "isNoJam", false);
        this.isNoSpentRoundChamber = ConfigUtils.getBooleanFromConfig(config, "isNoSpentRoundChamber", false);
        this.isNoBroken = ConfigUtils.getBooleanFromConfig(config, "isNoBroken", false);
        this.isNoInfected = ConfigUtils.getBooleanFromConfig(config, "isNoInfected", false);
        this.isNoWet = ConfigUtils.getBooleanFromConfig(config, "isNoWet", false);
        this.isNoHoled = ConfigUtils.getBooleanFromConfig(config, "isNoHoled", false);
        this.isNoDirted = ConfigUtils.getBooleanFromConfig(config, "isNoDirted", false);
        this.isNoBlooded = ConfigUtils.getBooleanFromConfig(config, "isNoBlooded", false);
        this.isBypassDebugMode = ConfigUtils.getBooleanFromConfig(config, "isBypassDebugMode", false);
        this.isUnlimitedCarry = ConfigUtils.getBooleanFromConfig(config, "isUnlimitedCarry", false);
        this.isUnlimitedCondition = ConfigUtils.getBooleanFromConfig(config, "isUnlimitedCondition", false);
        this.isUnlimitedEndurance = ConfigUtils.getBooleanFromConfig(config, "isUnlimitedEndurance", false);
        this.isUnlimitedAmmo = ConfigUtils.getBooleanFromConfig(config, "isUnlimitedAmmo", false);
        this.isDisableFatigue = ConfigUtils.getBooleanFromConfig(config, "isDisableFatigue", false);
        this.isDisableHunger = ConfigUtils.getBooleanFromConfig(config, "isDisableHunger", false);
        this.isDisableThirst = ConfigUtils.getBooleanFromConfig(config, "isDisableThirst", false);
        this.isDisableDrunkenness = ConfigUtils.getBooleanFromConfig(config, "isDisableDrunkenness", false);
        this.isDisableAnger = ConfigUtils.getBooleanFromConfig(config, "isDisableAnger", false);
        this.isDisableFear = ConfigUtils.getBooleanFromConfig(config, "isDisableFear", false);
        this.isDisablePain = ConfigUtils.getBooleanFromConfig(config, "isDisablePain", false);
        this.isDisablePanic = ConfigUtils.getBooleanFromConfig(config, "isDisablePanic", false);
        this.isDisableMorale = ConfigUtils.getBooleanFromConfig(config, "isDisableMorale", false);
        this.isDisableStress = ConfigUtils.getBooleanFromConfig(config, "isDisableStress", false);
        this.isDisableSickness = ConfigUtils.getBooleanFromConfig(config, "isDisableSickness", false);
        this.isDisableStressFromCigarettes = ConfigUtils.getBooleanFromConfig(config, "isDisableStressFromCigarettes", false);
        this.isDisableSanity = ConfigUtils.getBooleanFromConfig(config, "isDisableSanity", false);
        this.isDisableBoredomLevel = ConfigUtils.getBooleanFromConfig(config, "isDisableBoredomLevel", false);
        this.isDisableUnhappynessLevel = ConfigUtils.getBooleanFromConfig(config, "isDisableUnhappynessLevel", false);
        this.isDisableWetness = ConfigUtils.getBooleanFromConfig(config, "isDisableWetness", false);
        this.isDisableInfectionLevel = ConfigUtils.getBooleanFromConfig(config, "isDisableInfectionLevel", false);
        this.isDisableFakeInfectionLevel = ConfigUtils.getBooleanFromConfig(config, "isDisableFakeInfectionLevel", false);
        this.isDisableFire = ConfigUtils.getBooleanFromConfig(config, "isDisableFire", false);
        this.isOptimalCalories = ConfigUtils.getBooleanFromConfig(config, "isOptimalCalories", false);
        this.isOptimalWeight = ConfigUtils.getBooleanFromConfig(config, "isOptimalWeight", false);
        this.isVisualsEnable = ConfigUtils.getBooleanFromConfig(config, "isVisualsEnable", false);
        this.isVisualsPlayersEnable = ConfigUtils.getBooleanFromConfig(config, "isVisualsPlayersEnable", false);
        this.isVisualsVehiclesEnable = ConfigUtils.getBooleanFromConfig(config, "isVisualsVehiclesEnable", false);
        this.isVisualsZombiesEnable = ConfigUtils.getBooleanFromConfig(config, "isVisualsZombiesEnable", false);
        this.isVisualDrawToLocalPlayer = ConfigUtils.getBooleanFromConfig(config, "isVisualDrawToLocalPlayer", false);
        this.isVisualDrawPlayerNickname = ConfigUtils.getBooleanFromConfig(config, "isVisualDrawPlayerNickname", false);
        this.isVisualDrawPlayerInfo = ConfigUtils.getBooleanFromConfig(config, "isVisualDrawPlayerInfo", false);
        this.isVisualDrawLineToVehicle = ConfigUtils.getBooleanFromConfig(config, "isVisualDrawLineToVehicle", false);
        this.isVisualDrawLineToPlayers = ConfigUtils.getBooleanFromConfig(config, "isVisualDrawLineToPlayers", false);
        this.isVisualEnable360Vision = ConfigUtils.getBooleanFromConfig(config, "isVisualEnable360Vision", false);
        this.isMapDrawLocalPlayer = ConfigUtils.getBooleanFromConfig(config, "isMapDrawLocalPlayer", true);
        this.isMapDrawAllPlayers = ConfigUtils.getBooleanFromConfig(config, "isMapDrawAllPlayers", false);
        this.isMapDrawVehicles = ConfigUtils.getBooleanFromConfig(config, "isMapDrawVehicles", false);
        this.isMapDrawZombies = ConfigUtils.getBooleanFromConfig(config, "isMapDrawZombies", false);
        this.isMapDrawSurvivors = ConfigUtils.getBooleanFromConfig(config, "isMapDrawSurvivors", false);
        this.isMapDrawRemoteSurvivors = ConfigUtils.getBooleanFromConfig(config, "isMapDrawRemoteSurvivors", false);
        this.isMapDrawRooms = ConfigUtils.getBooleanFromConfig(config, "isMapDrawRooms", false);
        this.isMapDrawBuildings = ConfigUtils.getBooleanFromConfig(config, "isMapDrawBuildings", false);
        this.isMapDrawPushables = ConfigUtils.getBooleanFromConfig(config, "isMapDrawPushables", false);
    }

    private void initStartupConfig()
    {
        Properties config = new Properties();
        try (FileInputStream fis = new FileInputStream("EtherHack/config/startup.properties");)
        {
            if (Files.notExists(Paths.get("EtherHack","config")))
            {
                Files.createDirectories(Paths.get("EtherHack","config"));
                Files.createFile(Paths.get("EtherHack","config").resolve("startup.properties"));
            }

            config.load(fis);    
        }
        catch (IOException e) 
        {}

        //this. = ConfigUtils.getBooleanFromConfig(config, "", false);
        this.mainUIAccentColor = ConfigUtils.getColorFromConfig(config, "mainUIAccentColor", new Color(56, 239, 125));
        this.vehicleUIColor = ConfigUtils.getColorFromConfig(config, "vehicleUIColor", new Color(150, 150, 200));
        this.zombieUIColor = ConfigUtils.getColorFromConfig(config, "zombieUIColor", new Color(255, 150, 100));
        this.playerUIColor = ConfigUtils.getColorFromConfig(config, "playerUIColor", new Color(255, 50, 100));
        this.survivorUIColor = ConfigUtils.getColorFromConfig(config, "survivorUIColor", new Color(0, 0, 0));
        this.remoteSurvivorUIColor = ConfigUtils.getColorFromConfig(config, "remoteSurvivorUIColor", new Color(0, 0, 0));
        this.itemUIColor = ConfigUtils.getColorFromConfig(config, "itemUIColor", new Color(0, 0, 0));
        this.worldItemUIColor = ConfigUtils.getColorFromConfig(config, "worldItemUIColor", new Color(0, 0, 0));
        this.roomUIColor = ConfigUtils.getColorFromConfig(config, "roomUIColor", new Color(0, 0, 0));
        this.buildingUIColor = ConfigUtils.getColorFromConfig(config, "buildingUIColor", new Color(0, 0, 0));
        this.pushableUIColor = ConfigUtils.getColorFromConfig(config, "pushableUIColor", new Color(0, 0, 0));
        this.isAlwaysRack = ConfigUtils.getBooleanFromConfig(config, "isAlwaysRack", false);
        this.isAlwaysRoundChamber = ConfigUtils.getBooleanFromConfig(config, "isAlwaysRoundChamber", false);
        this.isAlwaysRepaired = ConfigUtils.getBooleanFromConfig(config, "isAlwaysRepaired", false);
        this.isAlwaysKnockdown = ConfigUtils.getBooleanFromConfig(config, "isAlwaysKnockdown", false);
        this.isAlwaysAiming = ConfigUtils.getBooleanFromConfig(config, "isAlwaysAiming", false);
        this.isAlwaysCritical = ConfigUtils.getBooleanFromConfig(config, "isAlwaysCritical", false);
        this.isPlayerInSafeTeleported = ConfigUtils.getBooleanFromConfig(config, "isPlayerInSafeTeleported", false);
        this.isMultiHitZombies = ConfigUtils.getBooleanFromConfig(config, "isMultiHitZombies", false);
        this.isTimedActionCheat = ConfigUtils.getBooleanFromConfig(config, "isTimedActionCheat", false);
        this.isEnableGodMode = ConfigUtils.getBooleanFromConfig(config, "isEnableGodMode", false);
        this.isEnableNoclip = ConfigUtils.getBooleanFromConfig(config, "isEnableNoclip", false);
        this.isEnableInvisible = ConfigUtils.getBooleanFromConfig(config, "isEnableInvisible", false);
        this.isEnableNightVision = ConfigUtils.getBooleanFromConfig(config, "isEnableNightVision", false);
        this.isZombieDontAttack = ConfigUtils.getBooleanFromConfig(config, "isZombieDontAttack", false);
        this.isNoRecoil = ConfigUtils.getBooleanFromConfig(config, "isNoRecoil", false);
        this.isNoReload = ConfigUtils.getBooleanFromConfig(config, "isNoReload", false);
        this.isNoJam = ConfigUtils.getBooleanFromConfig(config, "isNoJam", false);
        this.isNoSpentRoundChamber = ConfigUtils.getBooleanFromConfig(config, "isNoSpentRoundChamber", false);
        this.isNoBroken = ConfigUtils.getBooleanFromConfig(config, "isNoBroken", false);
        this.isNoInfected = ConfigUtils.getBooleanFromConfig(config, "isNoInfected", false);
        this.isNoWet = ConfigUtils.getBooleanFromConfig(config, "isNoWet", false);
        this.isNoHoled = ConfigUtils.getBooleanFromConfig(config, "isNoHoled", false);
        this.isNoDirted = ConfigUtils.getBooleanFromConfig(config, "isNoDirted", false);
        this.isNoBlooded = ConfigUtils.getBooleanFromConfig(config, "isNoBlooded", false);
        this.isBypassDebugMode = ConfigUtils.getBooleanFromConfig(config, "isBypassDebugMode", false);
        this.isUnlimitedCarry = ConfigUtils.getBooleanFromConfig(config, "isUnlimitedCarry", false);
        this.isUnlimitedCondition = ConfigUtils.getBooleanFromConfig(config, "isUnlimitedCondition", false);
        this.isUnlimitedEndurance = ConfigUtils.getBooleanFromConfig(config, "isUnlimitedEndurance", false);
        this.isUnlimitedAmmo = ConfigUtils.getBooleanFromConfig(config, "isUnlimitedAmmo", false);
        this.isDisableFatigue = ConfigUtils.getBooleanFromConfig(config, "isDisableFatigue", false);
        this.isDisableHunger = ConfigUtils.getBooleanFromConfig(config, "isDisableHunger", false);
        this.isDisableThirst = ConfigUtils.getBooleanFromConfig(config, "isDisableThirst", false);
        this.isDisableDrunkenness = ConfigUtils.getBooleanFromConfig(config, "isDisableDrunkenness", false);
        this.isDisableAnger = ConfigUtils.getBooleanFromConfig(config, "isDisableAnger", false);
        this.isDisableFear = ConfigUtils.getBooleanFromConfig(config, "isDisableFear", false);
        this.isDisablePain = ConfigUtils.getBooleanFromConfig(config, "isDisablePain", false);
        this.isDisablePanic = ConfigUtils.getBooleanFromConfig(config, "isDisablePanic", false);
        this.isDisableMorale = ConfigUtils.getBooleanFromConfig(config, "isDisableMorale", false);
        this.isDisableStress = ConfigUtils.getBooleanFromConfig(config, "isDisableStress", false);
        this.isDisableSickness = ConfigUtils.getBooleanFromConfig(config, "isDisableSickness", false);
        this.isDisableStressFromCigarettes = ConfigUtils.getBooleanFromConfig(config, "isDisableStressFromCigarettes", false);
        this.isDisableSanity = ConfigUtils.getBooleanFromConfig(config, "isDisableSanity", false);
        this.isDisableBoredomLevel = ConfigUtils.getBooleanFromConfig(config, "isDisableBoredomLevel", false);
        this.isDisableUnhappynessLevel = ConfigUtils.getBooleanFromConfig(config, "isDisableUnhappynessLevel", false);
        this.isDisableWetness = ConfigUtils.getBooleanFromConfig(config, "isDisableWetness", false);
        this.isDisableInfectionLevel = ConfigUtils.getBooleanFromConfig(config, "isDisableInfectionLevel", false);
        this.isDisableFakeInfectionLevel = ConfigUtils.getBooleanFromConfig(config, "isDisableFakeInfectionLevel", false);
        this.isDisableFire = ConfigUtils.getBooleanFromConfig(config, "isDisableFire", false);
        this.isOptimalCalories = ConfigUtils.getBooleanFromConfig(config, "isOptimalCalories", false);
        this.isOptimalWeight = ConfigUtils.getBooleanFromConfig(config, "isOptimalWeight", false);
        this.isVisualsEnable = ConfigUtils.getBooleanFromConfig(config, "isVisualsEnable", false);
        this.isVisualsPlayersEnable = ConfigUtils.getBooleanFromConfig(config, "isVisualsPlayersEnable", false);
        this.isVisualsVehiclesEnable = ConfigUtils.getBooleanFromConfig(config, "isVisualsVehiclesEnable", false);
        this.isVisualsZombiesEnable = ConfigUtils.getBooleanFromConfig(config, "isVisualsZombiesEnable", false);
        this.isVisualDrawToLocalPlayer = ConfigUtils.getBooleanFromConfig(config, "isVisualDrawToLocalPlayer", false);
        this.isVisualDrawPlayerNickname = ConfigUtils.getBooleanFromConfig(config, "isVisualDrawPlayerNickname", false);
        this.isVisualDrawPlayerInfo = ConfigUtils.getBooleanFromConfig(config, "isVisualDrawPlayerInfo", false);
        this.isVisualDrawLineToVehicle = ConfigUtils.getBooleanFromConfig(config, "isVisualDrawLineToVehicle", false);
        this.isVisualDrawLineToPlayers = ConfigUtils.getBooleanFromConfig(config, "isVisualDrawLineToPlayers", false);
        this.isVisualEnable360Vision = ConfigUtils.getBooleanFromConfig(config, "isVisualEnable360Vision", false);
        this.isMapDrawLocalPlayer = ConfigUtils.getBooleanFromConfig(config, "isMapDrawLocalPlayer", true);
        this.isMapDrawAllPlayers = ConfigUtils.getBooleanFromConfig(config, "isMapDrawAllPlayers", false);
        this.isMapDrawVehicles = ConfigUtils.getBooleanFromConfig(config, "isMapDrawVehicles", false);
        this.isMapDrawZombies = ConfigUtils.getBooleanFromConfig(config, "isMapDrawZombies", false);
        this.isMapDrawSurvivors = ConfigUtils.getBooleanFromConfig(config, "isMapDrawSurvivors", false);
        this.isMapDrawRemoteSurvivors = ConfigUtils.getBooleanFromConfig(config, "isMapDrawRemoteSurvivors", false);
        this.isMapDrawRooms = ConfigUtils.getBooleanFromConfig(config, "isMapDrawRooms", false);
        this.isMapDrawBuildings = ConfigUtils.getBooleanFromConfig(config, "isMapDrawBuildings", false);
        this.isMapDrawPushables = ConfigUtils.getBooleanFromConfig(config, "isMapDrawPushables", false);
    }
}
